name: Deploy on GHCR update

on:
  workflow_dispatch:
    inputs:
      api_name:
        description: "API to deploy"
        required: true
        type: choice
        options:
          - customer-api
          - core-api
  # registry_package:
  #   types:
  #     - published
  #     - updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    # if: |
    #   github.event.registry_package.package_type == 'container' &&
    #   (
    #     (
    #       github.event.registry_package.name == 'customer-api' ||
    #       github.event.registry_package.name == 'core-api'
    #     ) &&
    #     github.event.registry_package.package_version.name == 'latest'
    #   )

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Print the package name
        run: |
          echo "Package: ${{ inputs.api_name }}"
          # echo "Package: ${{ github.event.registry_package.name }}"
          # echo "Version: ${{ github.event.registry_package.tag }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::403959680151:role/github-actions-ssm-deploy-role

      - name: Build image name
        id: image
        run: |
          PACKAGE_NAME="${{ inputs.api_name }}"
          # PACKAGE_NAME="${{ github.event.registry_package.name }}"
          # TAG="${{ github.event.registry_package.package_version.name }}"

          IMAGE="ghcr.io/${{ github.repository_owner }}/${PACKAGE_NAME}:latest"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "Deploying image: $IMAGE"

      - name: Resolve EC2 instance ID from tag
        id: ec2
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --region ap-south-1 \
            --filters \
              "Name=tag:Name,Values=maal-prod-${{ inputs.api_name }}" \
              "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)

          echo "Instance ID: $INSTANCE_ID"
          echo "instance_id=$INSTANCE_ID" >> "$GITHUB_OUTPUT"

      - name: Run deploy.sh on EC2 using SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --region ap-south-1 \
            --targets "Key=tag:Name,Values=maal-prod-${{ inputs.api_name }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy GHCR image ${{ steps.image.outputs.image }}" \
            --parameters commands='[
              "sudo -u ec2-user /home/ec2-user/deploy.sh \"${{ steps.image.outputs.image }}\""
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --region ap-south-1 \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ steps.ec2.outputs.instance_id }}"
